USE webDevelopment;
INSERT INTO languagess (`language`, `versions`) VALUES ('JavaScript', '5');
INSERT INTO languagess (`language`, `versions`) VALUES ('PHP', '5.2');
INSERT INTO languagess (`language`, `versions`) VALUES ('PHP', '5.4');
INSERT INTO languagess (`language`, `versions`) VALUES ('HTML', '5.1');
INSERT INTO languagess (`language`, `versions`) VALUES ('JavaScript', '6');
INSERT INTO languagess (`language`, `versions`) VALUES ('JavaScript', '7');
INSERT INTO languagess (`language`, `versions`) VALUES ('JavaScript', '8');
INSERT INTO languagess (`language`, `versions`) VALUES ('PHP', '7');
INSERT INTO frameworks(`frameworks`, `version`) VALUES ('Symfony', '2.8');
INSERT INTO frameworks(`frameworks`, `version`) VALUES ('Symfony', '3');
INSERT INTO frameworks(`frameworks`, `version`) VALUES ('Jquery', '1.6');
INSERT INTO frameworks(`frameworks`, `version`) VALUES ('Jquery', '2.10');
